#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one real Firebase project, replacing the local emulator default
# (docs/adr/0006) so cross-device sync has somewhere real to talk to.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

if [[ ! -f firestore.rules || ! -f package.json ]]; then
  printf 'Run this from the times-tables-quizzer repo root (firestore.rules and package.json must be in the current directory).\n' >&2
  exit 1
fi

banner "Times Tables Quizzer — Firebase project setup"

stage "Create the Firebase project"
say "Everything so far (firebase.json, firestore.rules, cloudSync.ts) talks only"
say "to a local emulator - this stage creates the real, hosted project behind it."
open_url "https://console.firebase.google.com/"
step "Click 'Add project' / 'Create a project'."
step "Name it anything, e.g. 'times-tables-quizzer' - Firebase will append a"
step "  random suffix to the actual project ID if that name's taken, which is"
step "  completely fine; you'll copy the real ID from the console in a later step."
step "Decline Google Analytics when asked (this app doesn't use it) and finish"
step "  project creation."
pause "Project created and you're looking at its Firebase console home?"

stage "Enable Cloud Firestore"
say "This is the database the shared Profile documents live in."
step "In the left sidebar: Build > Firestore Database."
step "Click 'Create database'."
step "Choose 'Start in production mode' - firestore.rules already has real"
step "  access-control logic committed in this repo, not the wide-open"
step "  test-mode default, so production mode is the right starting point."
step "Pick any region - this is a single-family app, so the closest one to you"
step "  is fine and the choice barely matters."
pause "Firestore database created?"

stage "Enable Anonymous Authentication"
say "Every device signs in anonymously (docs/adr/0006) - this is a cheap bot"
say "deterrent, not the real access control (that's the exact Profile ID, which"
say "only a pairing link/QR code hands out)."
step "In the left sidebar: Build > Authentication."
step "Click 'Get started' if this is the first time you've opened Authentication."
step "Go to the 'Sign-in method' tab."
step "Click 'Anonymous' in the provider list, toggle Enable, and Save."
pause "Anonymous sign-in enabled?"

stage "Register a Web App and capture its config"
say "This is the one stage that produces real values - the 4 lines cloudSync.ts"
say "needs to stop defaulting to the local emulator."
step "In the left sidebar: click the gear icon > Project settings (or go to"
step "  Project Overview and click the '</>' web icon if no web app exists yet)."
step "Under 'Your apps', register a new Web app - nickname can be anything,"
step "  e.g. 'times-tables-quizzer-web'. Skip Firebase Hosting if it's offered;"
step "  this app deploys to GitHub Pages instead."
step "Firebase shows a firebaseConfig object. Copy each of these 4 values:"
say  "    apiKey, authDomain, projectId, appId"
note "  (Yes, these are meant to be public - Firebase's own design puts access"
note "   control in Firestore Security Rules, not in hiding this config. See"
note "   docs/adr/0006's security/cost section.)"
ask VITE_FIREBASE_API_KEY "Paste apiKey:"
ask VITE_FIREBASE_AUTH_DOMAIN "Paste authDomain:"
ask VITE_FIREBASE_PROJECT_ID "Paste projectId:"
ask VITE_FIREBASE_APP_ID "Paste appId:"
write_env VITE_FIREBASE_API_KEY "$VITE_FIREBASE_API_KEY"
write_env VITE_FIREBASE_AUTH_DOMAIN "$VITE_FIREBASE_AUTH_DOMAIN"
write_env VITE_FIREBASE_PROJECT_ID "$VITE_FIREBASE_PROJECT_ID"
write_env VITE_FIREBASE_APP_ID "$VITE_FIREBASE_APP_ID"
say "Also publishing these as GitHub repo *variables* (not secrets - see the"
say "note above) so the live GitHub Pages build can use real sync too, not just"
say "local dev. .github/workflows/ci.yml's deploy step already reads these."
set_var VITE_FIREBASE_API_KEY "$VITE_FIREBASE_API_KEY"
set_var VITE_FIREBASE_AUTH_DOMAIN "$VITE_FIREBASE_AUTH_DOMAIN"
set_var VITE_FIREBASE_PROJECT_ID "$VITE_FIREBASE_PROJECT_ID"
set_var VITE_FIREBASE_APP_ID "$VITE_FIREBASE_APP_ID"

stage "Point the Firebase CLI at this project and deploy the security rules"
say "firestore.rules in this repo is already written and already tested"
say "(firestore-tests/rules.test.ts) - this stage just ships it to the real"
say "project. Nothing to write by hand."
if ! command -v firebase >/dev/null 2>&1 && [[ ! -x node_modules/.bin/firebase ]]; then
  warn "firebase-tools not found - run 'npm install' in the repo root first, then re-run this stage."
else
  FIREBASE_CMD="firebase"
  command -v firebase >/dev/null 2>&1 || FIREBASE_CMD="node_modules/.bin/firebase"
  say "About to run: $FIREBASE_CMD login (skip if already logged in), then"
  say "  $FIREBASE_CMD use --add"
  say "  $FIREBASE_CMD deploy --only firestore:rules"
  if confirm "Run these now?"; then
    "$FIREBASE_CMD" login || true
    step "When prompted by 'use --add': pick the project you just created, and give"
    step "  it any alias (e.g. 'production') - 'default' also works fine."
    if "$FIREBASE_CMD" use --add && "$FIREBASE_CMD" deploy --only firestore:rules; then
      note "Rules deployed."
    else
      SKIPPED+=("firebase use --add && firebase deploy --only firestore:rules (something failed above - re-run by hand)")
    fi
  else
    SKIPPED+=("firebase login && firebase use --add && firebase deploy --only firestore:rules (run by hand later)")
  fi
fi

stage "Verify"
say "Sanity-checks that .env's new values actually produce a working build -"
say "does NOT start the preview server here, so this wizard can still show its"
say "closing summary afterward rather than blocking on a long-running process."
if confirm "Run 'npm run build' now?"; then
  if npm run build; then
    note "Build succeeded with the real config."
  else
    SKIPPED+=("npm run build failed - check the error above before trusting .env")
  fi
else
  note "Skipped - you can build any time with: npm run build"
fi
say "To actually verify sync end-to-end:"
step "Run: npm run preview"
step "Open the printed URL, tap 'Sync across devices' > 'Start sharing'."
step "Check the Firebase console's Firestore data tab for a real profiles/{id}"
step "  document."
open_url "https://console.firebase.google.com/project/_/firestore/data"

finish
note "Local dev (.env) and the live GitHub Pages deploy (repo variables) are both"
note "wired to the real project now. Emulator-based dev/tests (npm run dev with"
note "the emulator running, npm run test:rules, npm run test:e2e) are untouched -"
note "they still default to the emulator project regardless of .env."
